// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WW10_protocol.proto

#ifndef PROTOBUF_WW10_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_WW10_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ww10 {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WW10_5fprotocol_2eproto();
void protobuf_AssignDesc_WW10_5fprotocol_2eproto();
void protobuf_ShutdownFile_WW10_5fprotocol_2eproto();

class PrologBotDescription;

// ===================================================================

class PrologBotDescription : public ::google::protobuf::Message {
 public:
  PrologBotDescription();
  virtual ~PrologBotDescription();
  
  PrologBotDescription(const PrologBotDescription& from);
  
  inline PrologBotDescription& operator=(const PrologBotDescription& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PrologBotDescription& default_instance();
  
  void Swap(PrologBotDescription* other);
  
  // implements Message ----------------------------------------------
  
  PrologBotDescription* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrologBotDescription& from);
  void MergeFrom(const PrologBotDescription& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // required string prolog = 3;
  inline bool has_prolog() const;
  inline void clear_prolog();
  static const int kPrologFieldNumber = 3;
  inline const ::std::string& prolog() const;
  inline void set_prolog(const ::std::string& value);
  inline void set_prolog(const char* value);
  inline void set_prolog(const char* value, size_t size);
  inline ::std::string* mutable_prolog();
  
  // @@protoc_insertion_point(class_scope:ww10.PrologBotDescription)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::std::string* prolog_;
  static const ::std::string _default_prolog_;
  friend void  protobuf_AddDesc_WW10_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_WW10_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_WW10_5fprotocol_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static PrologBotDescription* default_instance_;
};
// ===================================================================


// ===================================================================

// PrologBotDescription

// required int32 id = 1;
inline bool PrologBotDescription::has_id() const {
  return _has_bit(0);
}
inline void PrologBotDescription::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 PrologBotDescription::id() const {
  return id_;
}
inline void PrologBotDescription::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required string name = 2;
inline bool PrologBotDescription::has_name() const {
  return _has_bit(1);
}
inline void PrologBotDescription::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& PrologBotDescription::name() const {
  return *name_;
}
inline void PrologBotDescription::set_name(const ::std::string& value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PrologBotDescription::set_name(const char* value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PrologBotDescription::set_name(const char* value, size_t size) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PrologBotDescription::mutable_name() {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// required string prolog = 3;
inline bool PrologBotDescription::has_prolog() const {
  return _has_bit(2);
}
inline void PrologBotDescription::clear_prolog() {
  if (prolog_ != &_default_prolog_) {
    prolog_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& PrologBotDescription::prolog() const {
  return *prolog_;
}
inline void PrologBotDescription::set_prolog(const ::std::string& value) {
  _set_bit(2);
  if (prolog_ == &_default_prolog_) {
    prolog_ = new ::std::string;
  }
  prolog_->assign(value);
}
inline void PrologBotDescription::set_prolog(const char* value) {
  _set_bit(2);
  if (prolog_ == &_default_prolog_) {
    prolog_ = new ::std::string;
  }
  prolog_->assign(value);
}
inline void PrologBotDescription::set_prolog(const char* value, size_t size) {
  _set_bit(2);
  if (prolog_ == &_default_prolog_) {
    prolog_ = new ::std::string;
  }
  prolog_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PrologBotDescription::mutable_prolog() {
  _set_bit(2);
  if (prolog_ == &_default_prolog_) {
    prolog_ = new ::std::string;
  }
  return prolog_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ww10

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WW10_5fprotocol_2eproto__INCLUDED
